version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/Application
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
  fpm:
    build: ./docker
    ports:
      - "9000:9000"
    volumes:
      - .:/Application
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: tictactoe_user
      MYSQL_PASSWORD: tictactoe_pass
      MYSQL_ROOT_PASSWORD: tictactoe_root_user
      MYSQL_DATABASE: tictactoe
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080