version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./php:/Application
      - ./php/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
  fpm:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./php:/Application
    links:
      - db
  node:
    build: ./docker/node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/Application
    links:
      - db
  next:
    build: ./docker/node
    ports:
      - "3001:3000"
    volumes:
      - ./next:/Application
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: tictactoe_user
      MYSQL_PASSWORD: tictactoe_pass
      MYSQL_ROOT_PASSWORD: tictactoe_root_user
      MYSQL_DATABASE: tictactoe
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080